### ISSUE TITLE
No authorization required for the backend API

### ISSUE THREAD

**Issue by s1155030353** [ierg4210/shop06#2]
In app.js, /admin is protected with "authRouter". However, it would only detect if the index page is empty. Therefore an attack can be done in the following way:

(1) Modify the form a bit (at admin login page):
![image](https://cloud.githubusercontent.com/assets/10591335/7497160/5991c3bc-f44b-11e4-9119-b8f26d9c2dad.png)
(2) Submitting:
![image](https://cloud.githubusercontent.com/assets/10591335/7497177/7884d84a-f44b-11e4-92e6-a75bc2bf2598.png)
(3) And a new category is there.

**Comment by dennislky** [comment]
Fixed now, solution: check req.session before applying any change to db in order to avoid backend change without auth

**Comment by s1155015396** [comment]
Fixed now, solution: check req.session before applying any change to db in order to avoid backend change without auth

**Comment by diaowenrui** [comment]
[TA comment] Security Issue. The shop owner admitted this issue.
